better screenshotOptions and qrread

diff --git a/.local/bin/qrread b/.local/bin/qrread
--- a/.local/bin/qrread
+++ b/.local/bin/qrread
@@ -1,3 +1,9 @@
 #!/bin/sh
 
-zbarimg "$(find "/home/xerkse/Pictures/Screenshots/" -type f | tail -n 1)"
+filePath="$(screenshotOptions -s)" || exit
+
+zbaroutput="$(zbarimg -q "$filePath")" || { notify-send "no QR code result"; exit 1; }
+result="$(echo "$zbaroutput" | sed "1s/^QR-Code://")"
+echo "$result"
+echo "$result" | xclip -selection clipboard || notify-send "failed to copy QR data to clipboard"
+notify-send "$result"
